[package]
name = "flash-macros"
version = "0.1.0"
authors = ["HJfod"]
description = "Macros for the Flash documentation generator"
license-file = "LICENSE"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.47"
convert_case = "0.1.0"
